version: "3"
services:
  build-img:
    build:
      context: ../
      dockerfile: docker/build.dockerfile
    image: wilsonny/goat-build:latest
  release-img:
    build:
      context: ../
      dockerfile: docker/release.dockerfile
    image: wilsonny/goat:latest
