name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Build
      run: ./build.sh build

    - name: Test
      run: ./build.sh test
